"""
Frontend handler for serving the SvelteKit frontend from FastAPI.
This module provides a simplified implementation for serving static files
generated by SvelteKit's adapter-static.
"""

import os
import pathlib
from fastapi import FastAPI, Request
from fastapi.responses import FileResponse, JSONResponse, HTMLResponse
from fastapi.staticfiles import StaticFiles
import logging

logger = logging.getLogger(__name__)


def setup_frontend(app: FastAPI):
    """
    Set up routes to serve the SvelteKit frontend from FastAPI.

    This function:
    1. Mounts static files from the build directory
    2. Serves the index.html file for SPA routing
    3. Ensures API routes are not intercepted by static file serving
    """
    # Path to the frontend static files (from the Docker build)
    static_dir = pathlib.Path("/app/static")

    # Check if the static directory exists
    if not static_dir.exists():
        logger.warning("Static directory not found at /app/static")
        return

    logger.info(f"Setting up frontend serving from {static_dir}")

    # Mount static assets directory for JS, CSS, and other assets
    # This handles all files in _app directory (immutable assets)
    if (static_dir / "_app").exists():
        app.mount(
            "/_app", StaticFiles(directory=str(static_dir / "_app")), name="static_app"
        )
        logger.info("Mounted /_app static files")

    # Mount other static files (favicon, robots.txt, etc.)
    static_files = ["favicon.png", "favicon.svg", "robots.txt", "manifest.json"]
    for static_file in static_files:
        file_path = static_dir / static_file
        if file_path.exists():

            @app.get(f"/{static_file}")
            async def serve_static_file(file_name=static_file):
                return FileResponse(str(static_dir / file_name))

    # SPA route handler - serve index.html for all non-API and non-static routes
    @app.get("/{full_path:path}")
    async def serve_spa(request: Request, full_path: str):
        # Skip API routes - these should be handled by FastAPI's router
        if full_path.startswith("api"):
            # This should not be reached if API routes are properly registered
            logger.warning(f"API route not handled by router: {full_path}")
            return JSONResponse(status_code=404, content={"detail": "Not Found"})

        # Check if the path exists as a static file first
        requested_path = static_dir / full_path
        if requested_path.exists() and requested_path.is_file():
            return FileResponse(str(requested_path))

        # For SPA routing, return the index.html file
        index_path = static_dir / "index.html"
        if index_path.exists():
            return FileResponse(str(index_path))

        # If index.html doesn't exist, return 404
        logger.error(f"index.html not found at {index_path}")
        return JSONResponse(status_code=404, content={"detail": "Frontend not found"})
